
package com.quantiguous.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "fundsTransferByCustomerService2HttpService", targetNamespace = "http://www.quantiguous.com/services", wsdlLocation = "file:/Users/akhileshkataria/Code/java/ft2/fundsTransferByCustomerService2.wsdl")
public class FundsTransferByCustomerService2HttpService
    extends Service
{

    private final static URL FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_EXCEPTION;
    private final static QName FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_QNAME = new QName("http://www.quantiguous.com/services", "fundsTransferByCustomerService2HttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/akhileshkataria/Code/java/ft2/fundsTransferByCustomerService2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_WSDL_LOCATION = url;
        FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_EXCEPTION = e;
    }

    public FundsTransferByCustomerService2HttpService() {
        super(__getWsdlLocation(), FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_QNAME);
    }

    public FundsTransferByCustomerService2HttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_QNAME, features);
    }

    public FundsTransferByCustomerService2HttpService(URL wsdlLocation) {
        super(wsdlLocation, FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_QNAME);
    }

    public FundsTransferByCustomerService2HttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_QNAME, features);
    }

    public FundsTransferByCustomerService2HttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FundsTransferByCustomerService2HttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FundsTransferByCustomerService2
     */
    @WebEndpoint(name = "fundsTransferByCustomerService2HttpPort")
    public FundsTransferByCustomerService2 getFundsTransferByCustomerService2HttpPort() {
        return super.getPort(new QName("http://www.quantiguous.com/services", "fundsTransferByCustomerService2HttpPort"), FundsTransferByCustomerService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FundsTransferByCustomerService2
     */
    @WebEndpoint(name = "fundsTransferByCustomerService2HttpPort")
    public FundsTransferByCustomerService2 getFundsTransferByCustomerService2HttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.quantiguous.com/services", "fundsTransferByCustomerService2HttpPort"), FundsTransferByCustomerService2.class, features);
    }

    /**
     * 
     * @return
     *     returns FundsTransferByCustomerService2
     */
    @WebEndpoint(name = "fundsTransferByCustomerService2HttpPortSoap11")
    public FundsTransferByCustomerService2 getFundsTransferByCustomerService2HttpPortSoap11() {
        return super.getPort(new QName("http://www.quantiguous.com/services", "fundsTransferByCustomerService2HttpPortSoap11"), FundsTransferByCustomerService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FundsTransferByCustomerService2
     */
    @WebEndpoint(name = "fundsTransferByCustomerService2HttpPortSoap11")
    public FundsTransferByCustomerService2 getFundsTransferByCustomerService2HttpPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.quantiguous.com/services", "fundsTransferByCustomerService2HttpPortSoap11"), FundsTransferByCustomerService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_EXCEPTION!= null) {
            throw FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_EXCEPTION;
        }
        return FUNDSTRANSFERBYCUSTOMERSERVICE2HTTPSERVICE_WSDL_LOCATION;
    }

}
