
package com.quantiguous.services;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "fundsTransferByCustomerService2", targetNamespace = "http://www.quantiguous.com/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FundsTransferByCustomerService2 {


    /**
     * The transfer funds to a beneficiary, the beneificiary could be pre-registered or specified at the time of the transaction. The method of transfer can specified or left to the service to choose.
     * 
     * @param remitterToBeneficiaryInfo
     * @param transactionStatus
     * @param transferAmount
     * @param uniqueResponseNo
     * @param version
     * @param requestReferenceNo
     * @param nameWithBeneficiaryBank
     * @param debitAccountNo
     * @param beneficiary
     * @param uniqueRequestNo
     * @param appID
     * @param purposeCode
     * @param customerID
     * @param transferType
     * @param attemptNo
     * @param transferCurrencyCode
     * @param lowBalanceAlert
     */
    @WebMethod(action = "http://www.quantiguous.com/services/transfer")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.TransferResponse")
    public void transfer(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "uniqueRequestNo", targetNamespace = "http://www.quantiguous.com/services")
        String uniqueRequestNo,
        @WebParam(name = "appID", targetNamespace = "http://www.quantiguous.com/services")
        String appID,
        @WebParam(name = "purposeCode", targetNamespace = "http://www.quantiguous.com/services")
        String purposeCode,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "debitAccountNo", targetNamespace = "http://www.quantiguous.com/services")
        String debitAccountNo,
        @WebParam(name = "beneficiary", targetNamespace = "http://www.quantiguous.com/services")
        BeneficiaryType beneficiary,
        @WebParam(name = "transferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<TransferTypeType> transferType,
        @WebParam(name = "transferCurrencyCode", targetNamespace = "http://www.quantiguous.com/services")
        CurrencyCodeType transferCurrencyCode,
        @WebParam(name = "transferAmount", targetNamespace = "http://www.quantiguous.com/services")
        float transferAmount,
        @WebParam(name = "remitterToBeneficiaryInfo", targetNamespace = "http://www.quantiguous.com/services")
        String remitterToBeneficiaryInfo,
        @WebParam(name = "uniqueResponseNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> uniqueResponseNo,
        @WebParam(name = "attemptNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<BigInteger> attemptNo,
        @WebParam(name = "lowBalanceAlert", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Boolean> lowBalanceAlert,
        @WebParam(name = "transactionStatus", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransactionStatusType> transactionStatus,
        @WebParam(name = "nameWithBeneficiaryBank", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> nameWithBeneficiaryBank,
        @WebParam(name = "requestReferenceNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> requestReferenceNo);

    /**
     * To pay an invoice received from a supplier. Details of the invoice can be supplied , and payment vouchers can be generated and sent to the suppliers for better and easier reconciliation.
     * 
     * @param debitAccountNo
     * @param uniqueRequestNo
     * @param supplier
     * @param customerID
     * @param transferType
     * @param invoice
     * @param paymentCurrency
     * @param netPayableAmount
     * @param uniqueResponseNo
     * @param version
     */
    @WebMethod(action = "http://www.quantiguous.com/services/payInvoice")
    @RequestWrapper(localName = "payInvoice", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.PayInvoice")
    @ResponseWrapper(localName = "payInvoiceResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.PayInvoiceResponse")
    public void payInvoice(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "uniqueRequestNo", targetNamespace = "http://www.quantiguous.com/services")
        String uniqueRequestNo,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "debitAccountNo", targetNamespace = "http://www.quantiguous.com/services")
        String debitAccountNo,
        @WebParam(name = "supplier", targetNamespace = "http://www.quantiguous.com/services")
        SupplierType supplier,
        @WebParam(name = "transferType", targetNamespace = "http://www.quantiguous.com/services")
        TransferTypeType transferType,
        @WebParam(name = "paymentCurrency", targetNamespace = "http://www.quantiguous.com/services")
        CurrencyCodeType paymentCurrency,
        @WebParam(name = "netPayableAmount", targetNamespace = "http://www.quantiguous.com/services")
        float netPayableAmount,
        @WebParam(name = "invoice", targetNamespace = "http://www.quantiguous.com/services")
        InvoiceType invoice,
        @WebParam(name = "uniqueResponseNo", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> uniqueResponseNo);

    /**
     * 
     * @param reqTransferType
     * @param transactionStatus
     * @param appID
     * @param customerID
     * @param transferAmount
     * @param transferType
     * @param transactionDate
     * @param version
     * @param transferCurrencyCode
     * @param requestReferenceNo
     */
    @WebMethod(action = "http://www.quantiguous.com/services/getStatus")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetStatusResponse")
    public void getStatus(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.INOUT)
        Holder<String> version,
        @WebParam(name = "appID", targetNamespace = "http://www.quantiguous.com/services")
        String appID,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "requestReferenceNo", targetNamespace = "http://www.quantiguous.com/services")
        String requestReferenceNo,
        @WebParam(name = "transferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransferTypeType> transferType,
        @WebParam(name = "reqTransferType", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransferTypeType> reqTransferType,
        @WebParam(name = "transactionDate", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> transactionDate,
        @WebParam(name = "transferAmount", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Float> transferAmount,
        @WebParam(name = "transferCurrencyCode", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<CurrencyCodeType> transferCurrencyCode,
        @WebParam(name = "transactionStatus", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<TransactionStatusType> transactionStatus);

    /**
     * 
     * @param accountCurrencyCode
     * @param version0
     * @param appID
     * @param accountBalanceAmount
     * @param customerID
     * @param accountNumber
     * @param version
     * @param lowBalanceAlert
     */
    @WebMethod(action = "http://www.quantiguous.com/services/getBalance")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://www.quantiguous.com/services", className = "com.quantiguous.services.GetBalanceResponse")
    public void getBalance(
        @WebParam(name = "version", targetNamespace = "http://www.quantiguous.com/services")
        String version,
        @WebParam(name = "appID", targetNamespace = "http://www.quantiguous.com/services")
        String appID,
        @WebParam(name = "customerID", targetNamespace = "http://www.quantiguous.com/services")
        String customerID,
        @WebParam(name = "AccountNumber", targetNamespace = "http://www.quantiguous.com/services")
        String accountNumber,
        @WebParam(name = "Version", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<String> version0,
        @WebParam(name = "accountCurrencyCode", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<CurrencyCodeType> accountCurrencyCode,
        @WebParam(name = "accountBalanceAmount", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Float> accountBalanceAmount,
        @WebParam(name = "lowBalanceAlert", targetNamespace = "http://www.quantiguous.com/services", mode = WebParam.Mode.OUT)
        Holder<Boolean> lowBalanceAlert);

}
